
import { Injectable } from '@angular/core';
import { Observable, of, Subject } from 'rxjs';
import { Mascota } from '../../model/mascota/mascota';

@Injectable({
  providedIn: 'root'
})
export class MascotasService {
  // Datos quemados para simular la base de datos
  private mockMascotas: Mascota[] = [
    {
      id: 1,
      vacunas: ['rabia', 'leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2018/09/14/07/57/yellow-lab-3676436_960_720.jpg',
      nombre: 'Fido',
      especie: 'Perro',
      raza: 'Labrador',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-10'),
      fechaNacimiento: new Date('2020-01-01'),
      peso: 30.5,
      microchipID: 123456
    },
    {
      id: 2,
      vacunas: ['rabia', 'triple felina', 'leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6',
      nombre: 'Whiskers',
      especie: 'Gato',
      raza: 'Siamés',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-01'),
      fechaNacimiento: new Date('2019-06-15'),
      peso: 10.2,
      microchipID: 654321
    },
    {
      id: 3,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://th.bing.com/th/id/OIP.-rfTw4F7s2A23HkQEOFC9wHaLH?w=139&h=208&c=7&r=0&o=7&pid=1.7&rm=3',
      nombre: 'Polly',
      especie: 'Loro',
      raza: 'Verde',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2021-03-10'),
      peso: 1.5,
      microchipID: 789012
    },
    {
      id: 4,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://www.monaconatureencyclopedia.com/wp-content/uploads/2008/08/3-Amphiprion-ocellaris-%C2%A9-Benoit-Lallement.jpg',
      nombre: 'Nemo',
      especie: 'Pez',
      raza: 'Payaso',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2022-07-20'),
      peso: 0.3,
      microchipID: 345678
    },
    {
      id: 5,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e',
      nombre: 'Max',
      especie: 'Perro',
      raza: 'Bulldog',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-14'),
      fechaNacimiento: new Date('2018-11-05'),
      peso: 25.0,
      microchipID: 987654
    },
    {
      id: 6,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6',
      nombre: 'Luna',
      especie: 'Gato',
      raza: 'Persa',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-10'),
      fechaNacimiento: new Date('2020-02-28'),
      peso: 12.0,
      microchipID: 456789
    },
    {
      id: 7,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://cdn.pixabay.com/photo/2018/05/21/01/24/parrot-3417217_640.jpg',
      nombre: 'Coco',
      especie: 'Loro',
      raza: 'Azul',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-12'),
      fechaNacimiento: new Date('2021-05-15'),
      peso: 1.8,
      microchipID: 159753
    },
    {
      id: 8,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://cdn.pixabay.com/photo/2020/02/28/20/10/pallet-doctor-fish-4888454_640.jpg',
      nombre: 'Dory',
      especie: 'Pez',
      raza: 'Cirujano',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-08-02'),
      fechaNacimiento: new Date('2022-08-30'),
      peso: 0.4,
      microchipID: 852963
    },
    {
      id: 9,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://cdn.britannica.com/80/29280-050-A3A13277/Beagles-pets.jpg?w=300',
      nombre: 'Bella',
      especie: 'Perro',
      raza: 'Beagle',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-08-07'),
      fechaNacimiento: new Date('2019-09-12'),
      peso: 20.0,
      microchipID: 741852
    },
    {
      id: 10,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://cdn.pixabay.com/photo/2021/01/15/17/37/cat-5919989_640.jpg',
      nombre: 'Simba',
      especie: 'Gato',
      raza: 'Maine Coon',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2020-05-20'),
      peso: 15.0,
      microchipID: 963852
    },
    {
      id: 11,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://th.bing.com/th/id/OIP.cOOc3HN0kTST8IXGjmYj0AHaNL?w=184&h=328&c=7&r=0&o=7&pid=1.7&rm=3',
      nombre: 'Kiara',
      especie: 'Loro',
      raza: 'Rojo',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2021-08-25'),
      peso: 2.0,
      microchipID: 357159
    },
    {
      id: 12,
      vacunas: ['leucemia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sano',
      foto: 'https://media.istockphoto.com/id/149081471/photo/blow-fish-frontal-view.jpg?s=1024x1024&w=is&k=20&c=OvzmoJ2Msj1In1Xl_BbfKnJSLFNs7sjwbtvu231bs6M=',
      nombre: 'Bubbles',
      especie: 'Pez',
      raza: 'Globo',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2022-09-10'),
      peso: 0.5,
      microchipID: 159753
    },
    {
      id: 13,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Con alergias',
      foto: 'https://cdn.pixabay.com/photo/2017/09/25/13/12/dog-2785074_960_720.jpg',
      nombre: 'Luna',
      especie: 'Perro',
      raza: 'Beagle',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-07-20'),
      fechaNacimiento: new Date('2019-05-15'),
      peso: 12.3,
      microchipID: 100002
    },
    {
      id: 14,
      vacunas: ['rabia', 'parvovirus'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2020/04/13/20/48/dog-5040008_640.jpg',
      nombre: 'Rocky',
      especie: 'Perro',
      raza: 'Bulldog',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-06-12'),
      fechaNacimiento: new Date('2018-03-12'),
      peso: 22.1,
      microchipID: 100003
    },
    {
      id: 15,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/02/15/12/12/cat-2068462_1280.jpg',
      nombre: 'Mishi',
      especie: 'Gato',
      raza: 'Siames',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-09-01'),
      fechaNacimiento: new Date('2021-02-10'),
      peso: 4.2,
      microchipID: 100004
    },
    {
      id: 16,
      vacunas: ['rabia'],
      alergias: ['asma'],
      observaciones: 'Tratamiento',
      foto: 'https://cdn.pixabay.com/photo/2025/05/07/21/35/golden-retriever-amber-blue-9586001_640.jpg',
      nombre: 'Toby',
      especie: 'Perro',
      raza: 'Golden Retriever',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-03-11'),
      fechaNacimiento: new Date('2017-06-20'),
      peso: 28.9,
      microchipID: 100005
    },
    {
      id: 17,
      vacunas: ['triple felina', 'rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/02/24/16/30/cat-2095559_640.jpg',
      nombre: 'Nina',
      especie: 'Gato',
      raza: 'Persa',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-11-05'),
      fechaNacimiento: new Date('2018-08-30'),
      peso: 3.6,
      microchipID: 100006
    },
    {
      id: 18,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Con dieta especial',
      foto: 'https://cdn.pixabay.com/photo/2019/12/24/13/20/dogs-4716735_640.jpg',
      nombre: 'Max',
      especie: 'Perro',
      raza: 'Cocker Spaniel',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-10-14'),
      fechaNacimiento: new Date('2020-04-11'),
      peso: 14.0,
      microchipID: 100007
    },
    {
      id: 19,
      vacunas: ['rabia'],
      alergias: ['dermatitis'],
      observaciones: 'En tratamiento',
      foto: 'https://cdn.pixabay.com/photo/2016/10/09/21/03/dog-1726930_640.jpg',
      nombre: 'Bruno',
      especie: 'Perro',
      raza: 'Pastor Alemán',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-05-09'),
      fechaNacimiento: new Date('2016-09-15'),
      peso: 35.2,
      microchipID: 100008
    },
    {
      id: 20,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2023/06/29/12/28/cats-8096304_640.jpg',
      nombre: 'Lola',
      especie: 'Gato',
      raza: 'Angora',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-07-17'),
      fechaNacimiento: new Date('2020-12-05'),
      peso: 4.7,
      microchipID: 100009
    },
    {
      id: 21,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2022/11/15/10/19/dog-7593666_640.jpg',
      nombre: 'Zeus',
      especie: 'Perro',
      raza: 'Dálmata',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-06-22'),
      fechaNacimiento: new Date('2019-01-10'),
      peso: 25.1,
      microchipID: 100010
    },
    {
      id: 22,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/06/26/12/39/husky-2443664_640.jpg',
      nombre: 'Simba',
      especie: 'Perro',
      raza: 'Husky',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-12-01'),
      fechaNacimiento: new Date('2018-07-21'),
      peso: 27.5,
      microchipID: 100011
    },
    {
      id: 23,
      vacunas: ['rabia'],
      alergias: ['alergia al polen'],
      observaciones: 'Controlada',
      foto: 'https://cdn.pixabay.com/photo/2021/11/05/19/30/animal-6771900_640.jpg',
      nombre: 'Mia',
      especie: 'Gato',
      raza: 'Bengala',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-11-11'),
      fechaNacimiento: new Date('2019-10-12'),
      peso: 5.4,
      microchipID: 100012
    },
    {
      id: 24,
      vacunas: ['rabia', 'leptospirosis'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2018/08/31/12/50/boxer-3644625_640.jpg',
      nombre: 'Thor',
      especie: 'Perro',
      raza: 'Boxer',
      sexo: 'Macho',
      estado: 'Control rutinario',
      ultimavisita: new Date('2025-08-08'),
      fechaNacimiento: new Date('2021-03-18'),
      peso: 29.3,
      microchipID: 100013
    },
    {
      id: 25,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2023/09/13/18/14/maine-coon-8250682_640.jpg',
      nombre: 'Sasha',
      especie: 'Gato',
      raza: 'Maine Coon',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-09-13'),
      fechaNacimiento: new Date('2018-12-01'),
      peso: 6.9,
      microchipID: 100014
    },
    {
      id: 26,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2024/02/17/00/18/cat-8578562_640.jpg',
      nombre: 'Felix',
      especie: 'Gato',
      raza: 'Europeo',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-07-19'),
      fechaNacimiento: new Date('2020-02-02'),
      peso: 4.3,
      microchipID: 100015
    },
    {
      id: 27,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2020/09/02/11/40/shih-tzu-5538105_640.jpg',
      nombre: 'Bobby',
      especie: 'Perro',
      raza: 'Shih Tzu',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-03-10'),
      fechaNacimiento: new Date('2019-11-11'),
      peso: 7.6,
      microchipID: 100016
    },
    {
      id: 28,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2022/05/03/17/43/animal-7172330_640.jpg',
      nombre: 'Coco',
      especie: 'Perro',
      raza: 'Poodle',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-05-21'),
      fechaNacimiento: new Date('2021-01-12'),
      peso: 6.1,
      microchipID: 100017
    },
    {
      id: 29,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2020/03/08/18/13/cats-4913336_640.jpg',
      nombre: 'Chispa',
      especie: 'Gato',
      raza: 'Abisinio',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-06-18'),
      fechaNacimiento: new Date('2020-09-01'),
      peso: 3.9,
      microchipID: 100018
    },
    {
      id: 30,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/09/13/16/22/belgian-2746075_1280.jpg',
      nombre: 'Rex',
      especie: 'Perro',
      raza: 'Pastor Belga',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-12-22'),
      fechaNacimiento: new Date('2017-05-23'),
      peso: 31.4,
      microchipID: 100019
    },
    {
      id: 31,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2013/09/03/23/30/animals-178808_640.jpg',
      nombre: 'Bella',
      especie: 'Perro',
      raza: 'Chihuahua',
      sexo: 'Hembra',
      estado: 'Control rutinario',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2021-06-06'),
      peso: 2.8,
      microchipID: 100020
    },
    {
      id: 32,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2016/11/26/23/47/cat-1861841_640.jpg',
      nombre: 'Tom',
      especie: 'Gato',
      raza: 'Siberiano',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-10-28'),
      fechaNacimiento: new Date('2018-07-19'),
      peso: 5.7,
      microchipID: 100021
    },
    {
      id: 33,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2021/07/06/14/38/border-collie-6391794_640.jpg',
      nombre: 'Maya',
      especie: 'Perro',
      raza: 'Border Collie',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-11-15'),
      fechaNacimiento: new Date('2019-08-30'),
      peso: 19.6,
      microchipID: 100022
    },
    {
      id: 34,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/03/14/14/49/cat-2143332_640.jpg',
      nombre: 'Kiara',
      especie: 'Gato',
      raza: 'British Shorthair',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-09-30'),
      fechaNacimiento: new Date('2020-05-15'),
      peso: 4.8,
      microchipID: 100023
    },
    {
      id: 35,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2021/10/14/17/58/dog-6710018_640.jpg',
      nombre: 'Jack',
      especie: 'Perro',
      raza: 'Rottweiler',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-04-12'),
      fechaNacimiento: new Date('2018-02-22'),
      peso: 33.5,
      microchipID: 100024
    },
    {
      id: 36,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2020/03/16/11/46/cat-4936769_640.jpg',
      nombre: 'Momo',
      especie: 'Gato',
      raza: 'Ragdoll',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-07-04'),
      fechaNacimiento: new Date('2019-09-14'),
      peso: 6.2,
      microchipID: 100025
    },
    {
      id: 37,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2016/04/27/17/28/snauzer-1357120_1280.jpg',
      nombre: 'Nico',
      especie: 'Perro',
      raza: 'Schnauzer',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-05-17'),
      fechaNacimiento: new Date('2020-06-30'),
      peso: 9.4,
      microchipID: 100026
    },
    {
      id: 38,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://delosgatosblog.com/wp-content/uploads/Gato-himalayo.webp',
      nombre: 'Lily',
      especie: 'Gato',
      raza: 'Himalayo',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-09-21'),
      fechaNacimiento: new Date('2019-11-07'),
      peso: 4.5,
      microchipID: 100027
    },
    {
      id: 39,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2015/11/12/20/32/st-bernard-1040956_640.jpg',
      nombre: 'Duke',
      especie: 'Perro',
      raza: 'San Bernardo',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-12-19'),
      fechaNacimiento: new Date('2017-10-16'),
      peso: 45.3,
      microchipID: 100028
    },
    {
      id: 40,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2018/01/07/15/46/pug-3067597_640.jpg',
      nombre: 'Tina',
      especie: 'Perro',
      raza: 'Pug',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-02-27'),
      fechaNacimiento: new Date('2020-04-09'),
      peso: 8.2,
      microchipID: 100029
    },
    {
      id: 41,
      vacunas: ['triple felina'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://estag.fimagenes.com/img/2/2/Z/c/5/2Zc5_900.jpg',
      nombre: 'Salem',
      especie: 'Gato',
      raza: 'Bombay',
      sexo: 'Macho',
      estado: 'Control rutinario',
      ultimavisita: new Date('2025-06-01'),
      fechaNacimiento: new Date('2021-07-07'),
      peso: 4.0,
      microchipID: 100030
    },
    {
      id: 42,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2016/07/28/20/28/standard-poodle-1549558_640.jpg',
      nombre: 'Daisy',
      especie: 'Perro',
      raza: 'Caniche',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-08-29'),
      fechaNacimiento: new Date('2018-05-05'),
      peso: 7.8,
      microchipID: 100031
    },
    {
      id: 43,
      vacunas: ['parvo'],
      alergias: ['ninguna conocida'],
      observaciones: 'En tratamiento',
      foto: 'https://cdn.pixabay.com/photo/2017/06/29/18/02/dog-2455272_640.jpg',
      nombre: 'Toby',
      especie: 'Perro',
      raza: 'Beagle',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-07-15'),
      fechaNacimiento: new Date('2019-05-21'),
      peso: 12.8,
      microchipID: 123501
    },
    {
      id: 44,
      vacunas: ['moquillo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2023/03/09/02/40/siberian-husky-7839113_640.jpg',
      nombre: 'Luna',
      especie: 'Perro',
      raza: 'Husky',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-09-10'),
      fechaNacimiento: new Date('2020-08-30'),
      peso: 18.3,
      microchipID: 123502
    },
    {
      id: 45,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2022/02/17/04/54/animal-7017939_1280.jpg',
      nombre: 'Mishu',
      especie: 'Gato',
      raza: 'Persa',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-06-12'),
      fechaNacimiento: new Date('2021-01-10'),
      peso: 6.1,
      microchipID: 123503
    },
    {
      id: 46,
      vacunas: ['triple felina'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2021/07/25/14/58/siamese-cat-6492109_640.jpg',
      nombre: 'Nina',
      especie: 'Gato',
      raza: 'Siamés',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-07-01'),
      fechaNacimiento: new Date('2022-02-14'),
      peso: 5.7,
      microchipID: 123504
    },
    {
      id: 47,
      vacunas: ['moquillo'],
      alergias: ['ninguna conocida'],
      observaciones: 'En tratamiento',
      foto: 'https://cdn.pixabay.com/photo/2020/02/29/04/45/german-shepherd-4889095_640.jpg',
      nombre: 'Zeus',
      especie: 'Perro',
      raza: 'Pastor Alemán',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-08-20'),
      fechaNacimiento: new Date('2018-09-11'),
      peso: 35.2,
      microchipID: 123505
    },
    {
      id: 48,
      vacunas: ['parvo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Recuperándose',
      foto: 'https://cdn.pixabay.com/photo/2025/07/25/17/29/dog-9735422_640.jpg',
      nombre: 'Kira',
      especie: 'Perro',
      raza: 'Golden Retriever',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-05-23'),
      fechaNacimiento: new Date('2021-11-19'),
      peso: 22.9,
      microchipID: 123506
    },
    {
      id: 49,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/01/21/18/15/cat-1997911_640.jpg',
      nombre: 'Simba',
      especie: 'Gato',
      raza: 'Angora',
      sexo: 'Macho',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-06-18'),
      fechaNacimiento: new Date('2020-03-05'),
      peso: 7.4,
      microchipID: 123507
    },
    {
      id: 50,
      vacunas: ['triple felina'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2020/10/05/10/51/cat-5628953_640.jpg',
      nombre: 'Mimi',
      especie: 'Gato',
      raza: 'Criollo',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-09-22'),
      fechaNacimiento: new Date('2022-04-21'),
      peso: 4.8,
      microchipID: 123508
    },
    {
      id: 51,
      vacunas: ['parvo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2019/05/07/20/44/dog-4187023_640.jpg',
      nombre: 'Rocky',
      especie: 'Perro',
      raza: 'Bulldog',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-07-28'),
      fechaNacimiento: new Date('2020-12-01'),
      peso: 20.6,
      microchipID: 123509
    },
    {
      id: 52,
      vacunas: ['moquillo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2016/01/11/22/36/dog-1134498_1280.jpg',
      nombre: 'Coco',
      especie: 'Perro',
      raza: 'Chihuahua',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-08-05'),
      fechaNacimiento: new Date('2021-07-07'),
      peso: 3.4,
      microchipID: 123510
    },
    {
      id: 53,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2022/09/06/07/49/cat-7436051_640.jpg',
      nombre: 'Pelusa',
      especie: 'Gato',
      raza: 'Maine Coon',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-06-11'),
      fechaNacimiento: new Date('2019-10-10'),
      peso: 8.9,
      microchipID: 123511
    },
    {
      id: 54,
      vacunas: ['triple felina'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2023/08/26/04/48/siberian-cat-8214143_640.jpg',
      nombre: 'Lolo',
      especie: 'Gato',
      raza: 'Siberiano',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-07-25'),
      fechaNacimiento: new Date('2020-06-13'),
      peso: 9.2,
      microchipID: 123512
    },
    {
      id: 55,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/10/02/21/04/doberman-2810203_640.png',
      nombre: 'Max',
      especie: 'Perro',
      raza: 'Doberman',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-05-14'),
      fechaNacimiento: new Date('2019-09-20'),
      peso: 32.1,
      microchipID: 123513
    },
    {
      id: 56,
      vacunas: ['moquillo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2017/07/20/03/50/poodle-2521137_640.jpg',
      nombre: 'Bella',
      especie: 'Perro',
      raza: 'Poodle',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-09-01'),
      fechaNacimiento: new Date('2022-03-12'),
      peso: 7.3,
      microchipID: 123514
    },
    {
      id: 57,
      vacunas: ['parvo'],
      alergias: ['ninguna conocida'],
      observaciones: 'En observación',
      foto: 'https://cdn.pixabay.com/photo/2019/12/24/13/20/dogs-4716740_640.jpg',
      nombre: 'Chester',
      especie: 'Perro',
      raza: 'Cocker Spaniel',
      sexo: 'Macho',
      estado: 'Control rutinario',
      ultimavisita: new Date('2025-07-07'),
      fechaNacimiento: new Date('2021-08-16'),
      peso: 14.4,
      microchipID: 123515
    },
    {
      id: 58,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2021/10/27/19/09/cat-6748193_640.jpg',
      nombre: 'Sasha',
      especie: 'Gato',
      raza: 'Bengalí',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-06-04'),
      fechaNacimiento: new Date('2020-09-23'),
      peso: 5.9,
      microchipID: 123516
    },
    {
      id: 59,
      vacunas: ['triple felina'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2016/02/10/16/37/cat-1192026_640.jpg',
      nombre: 'Felix',
      especie: 'Gato',
      raza: 'Criollo',
      sexo: 'Macho',
      estado: 'Control rutinario',
      ultimavisita: new Date('2025-08-09'),
      fechaNacimiento: new Date('2019-11-11'),
      peso: 4.6,
      microchipID: 123517
    },
    {
      id: 60,
      vacunas: ['moquillo'],
      alergias: ['ninguna conocida'],
      observaciones: 'Recuperándose',
      foto: 'https://cdn.pixabay.com/photo/2016/02/27/20/01/dog-1226205_1280.jpg',
      nombre: 'Bruno',
      especie: 'Perro',
      raza: 'San Bernardo',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-09-17'),
      fechaNacimiento: new Date('2018-04-14'),
      peso: 45.5,
      microchipID: 123518
    },
    {
      id: 61,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2022/04/15/11/23/dog-7134183_640.jpg',
      nombre: 'Daisy',
      especie: 'Perro',
      raza: 'Border Collie',
      sexo: 'Hembra',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-07-03'),
      fechaNacimiento: new Date('2021-10-22'),
      peso: 19.7,
      microchipID: 123519
    },
    {
      id: 62,
      vacunas: ['parvo'],
      alergias: ['ninguna conocida'],
      observaciones: 'En tratamiento',
      foto: 'https://cdn.pixabay.com/photo/2022/10/12/04/06/rottweiler-7515632_640.jpg',
      nombre: 'Rex',
      especie: 'Perro',
      raza: 'Rottweiler',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-08-28'),
      fechaNacimiento: new Date('2019-12-25'),
      peso: 40.2,
      microchipID: 123520
    },
    {
      id: 63,
      vacunas: ['rabia'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2025/06/02/21/36/cat-9637984_640.jpg',
      nombre: 'Cleo',
      especie: 'Gato',
      raza: 'Esfinge',
      sexo: 'Hembra',
      estado: 'Saludable',
      ultimavisita: new Date('2025-06-09'),
      fechaNacimiento: new Date('2020-02-28'),
      peso: 3.5,
      microchipID: 123521
    },
    {
      id: 64,
      vacunas: ['triple felina'],
      alergias: ['ninguna conocida'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2021/09/19/17/31/animal-6638652_640.jpg',
      nombre: 'Tom',
      especie: 'Gato',
      raza: 'British Shorthair',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-09-06'),
      fechaNacimiento: new Date('2021-05-09'),
      peso: 6.6,
      microchipID: 123522
    },
    {
      id: 65,
      vacunas: ['rabia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2018/08/31/12/50/boxer-3644625_640.jpg',
      nombre: 'Rocky',
      especie: 'Perro',
      raza: 'Boxer',
      sexo: 'Macho',
      estado: 'En tratamiento',
      ultimavisita: new Date('2025-07-10'),
      fechaNacimiento: new Date('2019-01-01'),
      peso: 28.0,
      microchipID: 221001
    },
    {
      id: 66,
      vacunas: ['leucemia'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2015/08/09/19/02/cat-882049_640.jpg',
      nombre: 'Michi',
      especie: 'Gato',
      raza: 'Siames',
      sexo: 'Hembra',
      estado: 'Recuperándose',
      ultimavisita: new Date('2025-06-20'),
      fechaNacimiento: new Date('2021-03-15'),
      peso: 5.0,
      microchipID: 221002
    },
    {
      id: 67,
      vacunas: ['moquillo'],
      alergias: ['ninguna'],
      observaciones: 'Sana',
      foto: 'https://cdn.pixabay.com/photo/2018/02/09/22/33/dog-3142750_640.jpg',
      nombre: 'Boby',
      especie: 'Perro',
      raza: 'Pug',
      sexo: 'Macho',
      estado: 'Saludable',
      ultimavisita: new Date('2025-05-15'),
      fechaNacimiento: new Date('2020-04-10'),
      peso: 7.5,
      microchipID: 221003
    }
  ];


  private mascotaAgregadaSource = new Subject<void>();
  mascotaAgregada$ = this.mascotaAgregadaSource.asObservable();

  constructor() { }

  getAllMascotas(): Observable<Mascota[]> {
    return of(this.mockMascotas);
  }

  getMascotaById(id: number): Observable<Mascota | undefined> {
    const mascota = this.mockMascotas.find(m => m.id === id);
    return of(mascota);
  }

  addMascota(mascota: Mascota): Observable<Mascota> {
    const newId = this.mockMascotas.length > 0 ? Math.max(...this.mockMascotas.map(m => m.id as number)) + 1 : 1;
    mascota.id = newId;
    this.mockMascotas.push(mascota);
    return of(mascota);
  }

  deleteMascota(id: number): Observable<void> {
    const index = this.mockMascotas.findIndex(m => m.id === id);
    if (index !== -1) {
      this.mockMascotas.splice(index, 1);
    }
    return of(undefined);
  }

   softDeleteMascota(mascota: Mascota): Observable<Mascota> {
    if (mascota.estado!.toLowerCase() === 'inactivo') {
      mascota.estado = mascota.estadoO !== "" ? String(mascota.estadoO) : "";
    } else {
      mascota.estadoO = mascota.estado;
      mascota.estado = 'inactivo';
    }
    return this.updateMascota(mascota);
  }

  updateMascota(mascota: Mascota): Observable<Mascota> {
    const index = this.mockMascotas.findIndex(m => m.id === mascota.id);
    if (index !== -1) {
      this.mockMascotas[index] = mascota;
    }
    return of(mascota);
  }

  notificarMascotaAgregada() {
    this.mascotaAgregadaSource.next();
  }

  getEdad(fechaNacimiento: Date | string): number {
  if (!fechaNacimiento) return 0;

  const f = (fechaNacimiento instanceof Date)
    ? fechaNacimiento
    : new Date(fechaNacimiento);

  const hoy = new Date();
  let edad = hoy.getFullYear() - f.getFullYear();
  const mes = hoy.getMonth() - f.getMonth();

  if (mes < 0 || (mes === 0 && hoy.getDate() < f.getDate())) {
    edad--;
  }

  return edad;
}

}
